#!/usr/bin/python3

import sys, os, requests, time

url = os.getenv('URL', 'https://diagnostic.opendns.com/myip')
user_agent = os.getenv('USER_AGENT', 'curl/7.58.0')

def myip():
    headers = { 'User-Agent': user_agent}

    while True:
        try:
            r = requests.get(url, headers=headers)
        except requests.exceptions.RequestException:
            time.sleep(1)
            pass
        if r.status_code == 200:
            return r.text.strip()
        else:
            time.sleep(5)


ip = myip()

prefix = os.getenv('PREFIX')
print("NAME: {}ip".format(prefix))
print("TAGS: ip")
print("METHOD: string|options=reinit dynamic")
print("DETAILS: {}".format(ip))
print("STATUS: {}".format(ip))
