#!/usr/bin/python3

import os
import sys

# read parameters
prefix = os.getenv('PREFIX')
maxlim = int(os.getenv('MAXLIM','2'))

load1, load5, load15 = os.getloadavg()

data = f"""
NAME: {prefix}la1
TAGS: la
METHOD: numerical|maxlim={maxlim}
STATUS: {load1:.3}

NAME: {prefix}la5
TAGS: la
METHOD: numerical|maxlim={maxlim}
STATUS: {load5:.3}

NAME: {prefix}la15
TAGS: la
METHOD: numerical|maxlim={maxlim}
STATUS: {load15:.3}

""".strip()

print(data)