#!/usr/bin/python3

import os
import sys

# read parameters
prefix = os.getenv('PREFIX')
period = int(os.getenv('PERIOD','15'))
maxlim = int(os.getenv('MAXLIM','2'))
basename = os.getenv('BASENAME')

if period not in [1, 5, 15]:
    period=15

load1, load5, load15 = os.getloadavg()

if period == 1:
    la = load1
elif period == 5:
    la = load5
else:
    la = load15

print("NAME: {}{}".format(prefix, basename))
print("TAGS: la")
print("METHOD: numerical|maxlim={}".format(maxlim))
print("STATUS: {}".format(la))
